version: "3.8"

services:
  mysql8:
    image: mysql:8.3
    container_name: flagr-mysql
    command: --default-authentication-plugin=mysql_native_password --general-log=1 --general-log-file=/var/lib/mysql/general-log.log
    ports:
      - "18100:3306"
    environment:
      MYSQL_DATABASE: flagr
      MYSQL_USER: flagr
      MYSQL_PASSWORD: flagr
      MYSQL_RANDOM_ROOT_PASSWORD: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  flagr:
    image: ghcr.io/openflagr/flagr
    container_name: flagr
    ports:
      - "18000:18000"
    environment:
      FLAGR_DB_DBDRIVER: "mysql"
      FLAGR_DB_DBCONNECTIONSTR: "flagr:flagr@tcp(flagr-mysql:3306)/flagr?parseTime=true"
    depends_on:
      mysql8:
        condition: service_healthy